name: Build Godot APK

on:
  workflow_dispatch:

env:
  GODOT_VERSION: 4.4

jobs:
  build-apk:
    name: Build Android APK Skirat-Games
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Godot Editor (${{ env.GODOT_VERSION }})
      run: |
        wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
        unzip Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip -d godot
        mv godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64 godot/godot
        chmod +x godot/godot
        echo "$GITHUB_WORKSPACE/godot" >> $GITHUB_PATH

    - name: Download Export Templates
      run: |
        wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
        mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable/
        unzip Godot_v${GODOT_VERSION}-stable_export_templates.tpz -d ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable/
        mv ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable/templates/* ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable/
    
    - name: Setup Android SDK
      env:
        ANDROID_SDK_ROOT: ${{ runner.tool_cache }}/android-sdk
      run: |
        mkdir -p $ANDROID_SDK_ROOT
        cd $ANDROID_SDK_ROOT

        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        rm cmdline-tools.zip

        mkdir -p cmdline-tools/latest
        mv cmdline-tools/{bin,lib,source.properties} cmdline-tools/latest/

        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-30" "build-tools;35.0.0"

    - name: Export Unsigned Android APK
      run: |
        mkdir -p build/android
        godot --headless --export-debug "Android" build/android/game.apk

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: godot-apk
        path: build/android/game.apk
