name: Build Mac (Godot)

on:
  workflow_dispatch:

env:
  GODOT_VERSION: 4.4

jobs:
  build-mac:
    name: Build Mac of Skirat-Games
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Godot Editor (${{ env.GODOT_VERSION }})
        run: |
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          unzip Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip -d godot
          mv godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64 godot/godot
          chmod +x godot/godot
          echo "$GITHUB_WORKSPACE/godot" >> $GITHUB_PATH

      - name: Download Export Templates
        run: |
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable/
          unzip Godot_v${GODOT_VERSION}-stable_export_templates.tpz -d ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable/
          mv ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable/templates/* ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable/

      - name: Create export output folder
        run: mkdir -p build/mac

      - name: Export Mac build
        run: |
          godot/godot --headless --export-release "macOS" build/mac/game.zip
        env:
          DISPLAY: ":0"

      - name: Upload artifact (Mac build)
        uses: actions/upload-artifact@v4
        with:
          name: godot-mac-build
          path: build/mac